version: '3'

services:
  server:
    build: "server"
    ports:
        - "8080:8080"
    depends_on:
        - postgres
    env_file:
        - .env

  postgres:
    build: "database"
    env_file:
        - .env
